### ISSUE TITLE
katakuna main dev & owner here

### ISSUE THREAD

**Issue by r0neko** [RinTinTinosu/AkemiSwitcher#1]
hi. we got notified about your repo.
you'd better fork it or we may take legal actions.
thank you!

**Comment by PoltixeTheDerg** [comment]
im just wondering why couldnt they fork it lmao
why does the readme say "pls for my sake let me not fork"

**Comment by r0neko** [comment]
i don't understand why they hate us in the first place. it seems like they have trouble setting up AkemiSwitcher. At least they could have contacted me lol

**Comment by PoltixeTheDerg** [comment]
osu! private server drama commence

**Comment by r0neko** [comment]
nah i don't do drama shit. i just take direct actions

**Comment by PoltixeTheDerg** [comment]
with how this person has acted so far, they might try to force drama, but I'm rooting for ur side

**Comment by RG6661** [comment]
not cool to steal switcher without fork >:(
bad boi

**Comment by RealistikDash** [comment]
It's generally not a really nice thing, not giving the actual creator the credit for the switcher he nicely open sourced for the community to use. Remember, he could have easily just not open sourced it and kept it to himself. So give him the small amount of credit with a fork, its easier than the process you have taken to not fork it. Anyways, why are you trying so hard not to fork it?

**Comment by the-source-hoarder** [comment]
ok man these are jokes don't take them literally!!! I am going to fork it or just delete it tbh it's dead server

**Comment by the-source-hoarder** [comment]
also I wasn't thinking straight there
